// <auto-generated />
using System;
using Coupon.Grpc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coupon.Grpc.Migrations
{
    [DbContext(typeof(Prn231GroupProjectContext))]
    [Migration("20241013120833_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coupon.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponCode = "WELCOME10",
                            CouponId = "81d422f6-9c43-4467-96aa-2d564a19b11a",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 10, 13, 12, 8, 32, 108, DateTimeKind.Utc).AddTicks(5417),
                            DiscountAmount = 10.0,
                            MaxAmount = 200.0,
                            MinAmount = 50.0,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CouponCode = "SUMMER20",
                            CouponId = "22816d9c-52b8-4916-a6c7-422110ec8a43",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 10, 13, 12, 8, 32, 108, DateTimeKind.Utc).AddTicks(5428),
                            DiscountAmount = 20.0,
                            MaxAmount = 500.0,
                            MinAmount = 100.0,
                            Quantity = 50,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
