// <auto-generated />
using System;
using Coupon.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coupon.API.Migrations
{
    [DbContext(typeof(Prn231GroupProjectContext))]
    [Migration("20241013103456_db")]
    partial class db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coupon.API.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MaxAmount")
                        .HasColumnType("float");

                    b.Property<double?>("MinAmount")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponCode = "WELCOME20",
                            CouponId = "1b4ec35c-8cb1-4241-a6e5-5dd96f25f4bb",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 10, 13, 10, 34, 55, 101, DateTimeKind.Utc).AddTicks(9504),
                            DiscountAmount = 20.0,
                            MaxAmount = 200.0,
                            MinAmount = 50.0,
                            Quantity = 10,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CouponCode = "SUMMER2024",
                            CouponId = "78bdadfb-e4e9-4017-8c77-ab26e9a1bb08",
                            CreatedBy = "Admin",
                            CreatedDate = new DateTime(2024, 10, 13, 10, 34, 55, 101, DateTimeKind.Utc).AddTicks(9514),
                            DiscountAmount = 50.0,
                            MaxAmount = 500.0,
                            MinAmount = 100.0,
                            Quantity = 5,
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
