// <auto-generated />
using System;
using Email.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Email.API.Migrations
{
    [DbContext(typeof(Prn231GroupProjectContext))]
    [Migration("20240927085930_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Email.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailTemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Body = "Hello! Thank you for joining us.",
                            Category = "Welcome",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 9, 27, 8, 59, 29, 609, DateTimeKind.Utc).AddTicks(3946),
                            Description = "Email sent to welcome new users.",
                            EmailTemplateId = "TEMPLATE_001",
                            Name = "Welcome Email",
                            Subject = "Welcome to Our Service!"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Body = "Click here to reset your password.",
                            Category = "Security",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2024, 9, 27, 8, 59, 29, 609, DateTimeKind.Utc).AddTicks(3955),
                            Description = "Email sent to reset user password.",
                            EmailTemplateId = "TEMPLATE_002",
                            Name = "Password Reset",
                            Subject = "Reset Your Password"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
