services:

  coupon.grpc:
    image: ${DOCKER_REGISTRY-}coupongrpc
    build:
      context: .
      dockerfile: Services/Coupon/Coupon.Grpc/Dockerfile

  messagebroker:
    image: rabbitmq:management 


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

