services:
  coupon.grpc:
    image: ${DOCKER_REGISTRY-}coupongrpc
    build:
      context: .
      dockerfile: Services/Coupon/Coupon.Grpc/Dockerfile
  email.service:
    image: ${DOCKER_REGISTRY-}emailservice
    build:
      context: .
      dockerfile: Services/Email/Email.API/Dockerfile


