services:

  coupon.grpc:
    image: ${DOCKER_REGISTRY-}coupongrpc
    build:
      context: .
      dockerfile: Services/Coupon/Coupon.Grpc/Dockerfile
      
  coupon.api:
    image: ${DOCKER_REGISTRY-}couponapi
    build:
      context: .
      dockerfile: Services/Coupon/Coupon.API/Dockerfile
      
  messagebroker:
    image: rabbitmq:management 

  rediscache:
    image: redis

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile
